/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AcademyRouteImport } from './routes/academy'
import { Route as ClipzoRouteImport } from './routes/clipzo'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as AcademyPageRouteImport } from './routes/academy.$page'
import { Route as ApiYoutubeReelsRouteImport } from './routes/api.youtube-reels'
import { Route as ClipzoPageRouteImport } from './routes/clipzo.$page'
import { Route as StudioPageRouteImport } from './routes/studio.$page'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyRoute = AcademyRouteImport.update({
  id: '/academy',
  path: '/academy',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipzoRoute = ClipzoRouteImport.update({
  id: '/clipzo',
  path: '/clipzo',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademyPageRoute = AcademyPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => AcademyRoute,
} as any)
const ApiYoutubeReelsRoute = ApiYoutubeReelsRouteImport.update({
  id: '/api/youtube-reels',
  path: '/api/youtube-reels',
  getParentRoute: () => rootRouteImport,
} as any)
const ClipzoPageRoute = ClipzoPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => ClipzoRoute,
} as any)
const StudioPageRoute = StudioPageRouteImport.update({
  id: '/$page',
  path: '/$page',
  getParentRoute: () => StudioRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/clipzo': typeof ClipzoRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/academy/$page': typeof AcademyPageRoute
  '/api/youtube-reels': typeof ApiYoutubeReelsRoute
  '/clipzo/$page': typeof ClipzoPageRoute
  '/studio/$page': typeof StudioPageRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/clipzo': typeof ClipzoRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/academy/$page': typeof AcademyPageRoute
  '/api/youtube-reels': typeof ApiYoutubeReelsRoute
  '/clipzo/$page': typeof ClipzoPageRoute
  '/studio/$page': typeof StudioPageRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/academy': typeof AcademyRouteWithChildren
  '/clipzo': typeof ClipzoRouteWithChildren
  '/studio': typeof StudioRouteWithChildren
  '/academy/$page': typeof AcademyPageRoute
  '/api/youtube-reels': typeof ApiYoutubeReelsRoute
  '/clipzo/$page': typeof ClipzoPageRoute
  '/studio/$page': typeof StudioPageRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/academy'
    | '/clipzo'
    | '/studio'
    | '/academy/$page'
    | '/api/youtube-reels'
    | '/clipzo/$page'
    | '/studio/$page'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/academy'
    | '/clipzo'
    | '/studio'
    | '/academy/$page'
    | '/api/youtube-reels'
    | '/clipzo/$page'
    | '/studio/$page'
  id:
    | '__root__'
    | '/'
    | '/academy'
    | '/clipzo'
    | '/studio'
    | '/academy/$page'
    | '/api/youtube-reels'
    | '/clipzo/$page'
    | '/studio/$page'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AcademyRoute: typeof AcademyRouteWithChildren
  ClipzoRoute: typeof ClipzoRouteWithChildren
  StudioRoute: typeof StudioRouteWithChildren
  ApiYoutubeReelsRoute: typeof ApiYoutubeReelsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy': {
      id: '/academy'
      path: '/academy'
      fullPath: '/academy'
      preLoaderRoute: typeof AcademyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clipzo': {
      id: '/clipzo'
      path: '/clipzo'
      fullPath: '/clipzo'
      preLoaderRoute: typeof ClipzoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academy/$page': {
      id: '/academy/$page'
      path: '/$page'
      fullPath: '/academy/$page'
      preLoaderRoute: typeof AcademyPageRouteImport
      parentRoute: typeof AcademyRoute
    }
    '/api/youtube-reels': {
      id: '/api/youtube-reels'
      path: '/api/youtube-reels'
      fullPath: '/api/youtube-reels'
      preLoaderRoute: typeof ApiYoutubeReelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clipzo/$page': {
      id: '/clipzo/$page'
      path: '/$page'
      fullPath: '/clipzo/$page'
      preLoaderRoute: typeof ClipzoPageRouteImport
      parentRoute: typeof ClipzoRoute
    }
    '/studio/$page': {
      id: '/studio/$page'
      path: '/$page'
      fullPath: '/studio/$page'
      preLoaderRoute: typeof StudioPageRouteImport
      parentRoute: typeof StudioRoute
    }
  }
}

interface AcademyRouteChildren {
  AcademyPageRoute: typeof AcademyPageRoute
}

const AcademyRouteChildren: AcademyRouteChildren = {
  AcademyPageRoute: AcademyPageRoute,
}

const AcademyRouteWithChildren =
  AcademyRoute._addFileChildren(AcademyRouteChildren)

interface ClipzoRouteChildren {
  ClipzoPageRoute: typeof ClipzoPageRoute
}

const ClipzoRouteChildren: ClipzoRouteChildren = {
  ClipzoPageRoute: ClipzoPageRoute,
}

const ClipzoRouteWithChildren =
  ClipzoRoute._addFileChildren(ClipzoRouteChildren)

interface StudioRouteChildren {
  StudioPageRoute: typeof StudioPageRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioPageRoute: StudioPageRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AcademyRoute: AcademyRouteWithChildren,
  ClipzoRoute: ClipzoRouteWithChildren,
  StudioRoute: StudioRouteWithChildren,
  ApiYoutubeReelsRoute: ApiYoutubeReelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
